### ISSUE TITLE
Suggestion: display two months in saturn datepicker

### ISSUE THREAD

**Issue by aberbenni** [SaturnTeam/saturn-datepicker#37] opened 2018-09-13 08:19 UTC
Like: 
![two-months-datepicker](https://user-images.githubusercontent.com/1632412/45475990-23b94580-b73e-11e8-9ee2-b7312be62c16.png)

**Comment by SaturnTeam** [comment] 2018-09-13 08:41
duplicate of #5

**Closed by SaturnTeam** 2018-09-13 08:41 UTC
