### ISSUE TITLE
FilterDate is not being fired initially

### ISSUE THREAD

**Issue by Cacanny** [SaturnTeam/saturn-datepicker#82] opened 2019-04-09 12:15 UTC
I have a filterDate which I pass in that will either disable or enable that month selection. But it doesn't get updated the first time you're in the view.

https://giphy.com/gifs/oOLF8npPEAQLgE1q8y

The above gif shows what is happening:

my code for this:

```
// left out imports
import { DatePickerHeaderComponent } from './header/date-picker-header.component';

@Component({
// not important
})
export class DatePickerComponent implements OnInit, OnChanges, AfterViewInit {
  datePickerHeader = DatePickerHeaderComponent;
  @Input() placement: Placement;
  @Input() placementTimesheets: PlacementTimesheet[];
  @Output() readonly updateDateRange: EventEmitter<SatDatepickerRangeValue<Date>> = new EventEmitter();
  @ViewChild('calendar') calendar: SatCalendar<Date>;
  minDate: Date;
  maxDate: Date;
  startAt: Date;
  beginDate: Date;
  endDate: Date;
  filterDate: any;
  range?: SatDatepickerRangeValue<Date>;

  constructor(
    private readonly dateAdapter: DateAdapter<Date>,
    private readonly route: ActivatedRoute,
    private readonly changeDetectorRef: ChangeDetectorRef,
  ) {}

  ngOnInit(): void {
    this.dateAdapter.getFirstDayOfWeek = () => 1;
  }

  ngAfterViewInit(): void {
    const params = this.route.snapshot.queryParams;
    this.startAt = new Date(params.year, params.month - 1);
    this.changeDetectorRef.detectChanges();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes.placement) {
      if (this.placement) {
        this.minDate = new Date(this.placement.startDate);
        this.maxDate = new Date(this.placement.endDate);
      }
    }

    if (changes.placementTimesheets) {
      if (this.placementTimesheets) {
        this.onMonthChange(this.calendar);
      }
    }
  }

  onMonthChange(calendar: SatCalendar<Date>): void {
    const activeTimesheetPlacement = this.getActivePlacementTimesheet(calendar);
    const enabledPlacementStatus = [1, 2, 3]; // not important
    typeof activeTimesheetPlacement !== 'undefined' && !enabledPlacementStatus.includes(activeTimesheetPlacement.status)
      ? (this.filterDate = (d: Date): boolean => false)
      : (this.filterDate = (d: Date): boolean => true);
  }

  onDateRangesChange(range: SatDatepickerRangeValue<Date>): void {
    this.beginDate = range.begin;
    this.endDate = range.end;
    this.range = range;
    this.updateDateRange.emit(this.range);
  }

  private getActivePlacementTimesheet(calendar: SatCalendar<Date>): PlacementTimesheet {
    // get current month (0-11)
    let activeMonth = new Date().getMonth();
    let activeYear = new Date().getFullYear();

    if (typeof calendar !== 'undefined') {
      activeMonth = new Date(calendar.activeDate).getMonth();
      activeYear = new Date(calendar.activeDate).getFullYear();
    }

    // Add 1 to make months 1-12
    activeMonth = activeMonth + 1;

    return this.placementTimesheets.find(x => x.year === activeYear && x.month === activeMonth);
  }
}
```
```
   <sat-calendar
      #calendar
      [headerComponent]="datePickerHeader"
      [dateFilter]="filterDate"
      [rangeMode]="true"
      [minDate]="minDate"
      [maxDate]="maxDate"
      [startAt]="startAt"
      [beginDate]="beginDate"
      [endDate]="endDate"
      orderPeriodLabel="month"
      (dateRangesChange)="onDateRangesChange($event)"
      (click)="onMonthChange(calendar)"
    ></sat-calendar>
  </div>
```

If this is more a stackoverflow issue, let me know.

**Comment by SaturnTeam** [comment] 2019-04-09 12:24
You are using calendar separately of input?

**Comment by Cacanny** [comment] 2019-04-09 12:41
Yes, correct, our business wants to have a calendar view unfortunately.

**Comment by SaturnTeam** [comment] 2019-04-09 12:50
Material calendar is not designed to use separately from datepicker

**Comment by Cacanny** [comment] 2019-04-09 13:17
So there's no way I can do this in the current solution?

**Comment by SaturnTeam** [comment] 2019-05-16 08:54
Duplicate of #40

**Closed by SaturnTeam** 2019-05-16 08:54 UTC
